---
AllProducts_lst: //div[@id='cartModal']/following::div[@class='col-sm-4']
View_Product_btn: (//div[@class='col-sm-4']//ul/li/a)[1]
ProductSearch_txtbx: //input[@id='search_product']
Search_btn: //button[@id='submit_search']